site_name: PLT
use_directory_urls: false
theme:
  name: material
  palette:
    - scheme: default
      primary: white
      accent: pink
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: pink
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - search
  - bibtex:
      bib_file: bibliography.bib
      cite_style: "plain"
      csl_file: harvard.csl
      bib_command: \bibliography
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true